Play travis
otus-devops-2019-05/atsip76_infra pull request #2
Opened 2019-06-17 07:16 UTC by atsip76

2019-06-17 08:28 UTC, enkov reviewed
Добрый день!
Поправьте тест и сделайте описание пулл реквеста.

2019-06-17 09:45 UTC, mrgreyves requested changes
Возвращено на доработку.

2019-06-17 14:07 UTC, atsip76 reviewed
Исправил проверку равенства аргументов

2019-06-17 14:11 UTC, atsip76 reviewed
Исправлен тест равенства аргументов

2019-06-18 06:36 UTC, atsip76 commented
- произведено клонирование именного репозитория для интеграций
- создана директория .github
- добавлен шаблон readme pull request
- добавлен файл проверок .travis.yml в корень репозитория
- выполнен коммит & push
- произведена регистрация в отделенном work space Slack и создан именной канал 
- приглашены в канал преподаватели для проверок
- приведена интеграция сознанного канала anatoly_afanasyev с github
- произведена авторизация на travis-ci.com
- произведен вход с консоли клиентом travis
- создана новая конфигурация travis c привязкой к созданному каналу anatoly_afanasyev 
- произведена интеграция именного канала anatoly_afanasyev c travis ci
- приведена настройка шифрования токена travis 
- выполнен коммит & push
- в директорию play-travis скачен файл test.py
- выполнен коммит & push
- тест провален, с уведомлением от travis ci в именном канале
- выполнено редактирование файла test.py исправлен тест равенства аргументов
- выполнен коммит & push
- тест пройден с уведомлением от travis ci об успешном прохождении теста последнего коммита

2019-06-18 07:20 UTC, mrgreyves approved these changes
Вот теперь уже хорошо. Принимаю!=)

2019-06-18 07:54 UTC, merged